version: '3.8'

services:
  # postgres:
  #   container_name: 'constructora_postgres'
  #   image: 'postgres:13'
  #   ports:
  #     - '127.0.0.1:5432:5432'
  #   volumes:
  #     - 'pgdata:/var/lib/postgresql/data'
  #   environment:
  #     - POSTGRES_DB=${POSTGRES_DB}
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_HOST_AUTH_METHOD=trust
    
  backend:
    container_name: 'constructora_backend'
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: 'always'
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    volumes:
      - './backend:/app'
    # depends_on:
    #   - postgres
  
  frontend:
    container_name: 'constructora_frontend'
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: 'always'
    env_file:
      - '.env'
    volumes:
      - './frontend/constructora-frontend:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true

# volumes:
#   pgdata: