services:
  backend:
    container_name: 'constructora_backend'
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: 'always'
    env_file:
      - '.env'
    ports:
      - '8000:8000'
    volumes:
      - './backend:/app'
  
  frontend:
    container_name: 'constructora_frontend'
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: 'always'
    env_file:
      - '.env'
    volumes:
      - './frontend/constructora-frontend:/app'
      - '/app/node_modules'
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
