# Generated by Django 5.0.4 on 2024-04-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cargo',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(default=None, max_length=100, verbose_name='Apellido'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
