# Generated by Django 5.0.6 on 2024-05-22 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constructora_App', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
