# Generated by Django 5.0.6 on 2024-05-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora_App', '0005_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('id_type', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('Gerente', 'Gerente'), ('Director de obra', 'Director de obra'), ('Capataz de obra', 'Capataz de obra'), ('Peón', 'Peón'), ('Ayudante de albañil', 'Ayudante de albañil')], max_length=20)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
