# Generated by Django 5.0.6 on 2024-06-04 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructora_App', '0006_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('asignada', 'Asignada'), ('en desarrollo', 'En Desarrollo'), ('en revisión', 'En Revisión'), ('aceptada', 'Aceptada')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('work_type', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('assistants', models.ManyToManyField(limit_choices_to={'role': 'Ayudante de albañil'}, related_name='work_assistants', to='constructora_App.userprofile')),
                ('director', models.ForeignKey(limit_choices_to={'role': 'Director de obra'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_director', to='constructora_App.userprofile')),
                ('foreman', models.ForeignKey(limit_choices_to={'role': 'Capataz de obra'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_foreman', to='constructora_App.userprofile')),
                ('laborers', models.ManyToManyField(limit_choices_to={'role': 'Peón'}, related_name='work_laborers', to='constructora_App.userprofile')),
            ],
        ),
    ]
